<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>RutaSegura.Notification.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../RutaSegura.Notification.Application/RutaSegura.Notification.Application.csproj" />
    <ProjectReference Include="../RutaSegura.Notification.Infrastructure/RutaSegura.Notification.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>
</Project>
