<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>RutaSegura.IAM.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../RutaSegura.IAM.Application/RutaSegura.IAM.Application.csproj" />
    <ProjectReference Include="../RutaSegura.IAM.Infrastructure/RutaSegura.IAM.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>
</Project>
