<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>RutaSegura.Administration.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../RutaSegura.Administration.Application/RutaSegura.Administration.Application.csproj" />
    <ProjectReference Include="../RutaSegura.Administration.Infrastructure/RutaSegura.Administration.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>
</Project>
