<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>RutaSegura.IAM.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../RutaSegura.IAM.Domain/RutaSegura.IAM.Domain.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(UseBuildingBlockPackages)' != 'true'">
    <ProjectReference Include="../../../../BuildingBlocks/RutaSegura.BuildingBlocks.Application/RutaSegura.BuildingBlocks.Application.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(UseBuildingBlockPackages)' == 'true'">
    <PackageReference Include="RutaSegura.BuildingBlocks.Application" Version="$(BuildingBlocksVersion)" />
  </ItemGroup>
</Project>
